name: Rebuild prod environment

on:
  workflow_dispatch:
  push:
    branches:
      - UNUSED

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    secrets:
      webhook_url: ${{ secrets.PORTAINER_PROD_APP_WEBHOOK_URL }}